#!/bin/bash

pushd /home/gy/progs/bygfoot/current-unstable/support_files
rm -f `find lg_commentary/ -name '*~'`
tar cfj bygfoot-1.9-commentaries.tar.bz2 lg_commentary
scf bygfoot-1.9-commentaries.tar.bz2 misc && rm -f bygfoot-1.9-commentaries.tar.bz2
popd
